KleyTech/Areas/Admin/Controllers/HeadersController.cs
using KleyTech.Data;
using KleyTech.DataAccess.Data.Repository.IRepository;
using KleyTech.Models;
using KleyTech.Models.ViewModels;
using KleyTech.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Packaging.Signing;

namespace KleyTech.Areas.Admin.Controllers
{
    [Authorize(Roles = CNT.Admin)]
    [Area("Admin")]
    public class HeadersController : Controller
    {
        private readonly IWorkContainer _workContainer;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public HeadersController(IWorkContainer workContainer, IWebHostEnvironment webHostEnvironment)
        {
            _workContainer = workContainer;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            //return View();
            return RedirectToAction("Edit", new { Id = 1 }); ;
        }

        //[HttpGet]
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Create(Header header)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        string MainRoute = _webHostEnvironment.WebRootPath;
        //        var files = HttpContext.Request.Form.Files;
        //        var headerFromDB = _workContainer.Header.Get(header.Id);

        //        if (files.Count > 0)
        //        {
        //            string fileName = Guid.NewGuid().ToString();
        //            var extension = Path.GetExtension(files[0].FileName);
        //            var uploads = Path.Combine(MainRoute, @"images\headers");

        //            using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
        //            {
        //                files[0].CopyTo(fileStream);
        //            }

        //            header.LogoURL = @"\images\headers\" + fileName + extension;

        //        }

        //        _workContainer.Header.Add(header);
        //        _workContainer.Save();

        //        return RedirectToAction(nameof(Index));
        //    }

        //    return View(header);

        //}

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Header header = _workContainer.Header.Get(id);
            if (header == null)
            {
                //return NotFound();
                header = new Header { Name = "Main header" };
                _workContainer.Header.Add(header);
                _workContainer.Save();
            }

            return View(header);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Header header)
        {

            if (ModelState.IsValid)
            {
                string MainRoute = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                var headerFromDB = _workContainer.Header.Get(header.Id);

                if (files.Count > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var extension = Path.GetExtension(files[0].FileName);
                    var uploads = Path.Combine(MainRoute, @"images\headers");

                    if (headerFromDB.LogoURL != null && headerFromDB.LogoURL.Length > 0)
                    {
                        var imageRoute = Path.Combine(MainRoute, headerFromDB.LogoURL.TrimStart('\\'));
                        if (System.IO.File.Exists(imageRoute))
                        {
                            System.IO.File.Delete(imageRoute);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }

                    header.LogoURL = @"\images\headers\" + fileName + extension;

                }
                else
                {
                    header.LogoURL = headerFromDB.LogoURL;
                }

                _workContainer.Header.Update(header);
                _workContainer.Save();

                return RedirectToAction(nameof(Areas.User.Controllers.HomeController.Index));
            }

            return View(header);

        }

        #region Call to API

        [HttpGet]
        public IActionResult GetAll()
        {
            //Opcion1
            return Json(new { data = _workContainer.Header.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var headerFromDb = _workContainer.Header.Get(id);
            string imageMainRoute = _webHostEnvironment.WebRootPath;
            if (headerFromDb.LogoURL != null)
            {
                var imageRoute = Path.Combine(imageMainRoute, headerFromDb.LogoURL.TrimStart('\\'));
                if (System.IO.File.Exists(imageRoute))
                {
                    System.IO.File.Delete(imageRoute);
                }
            }
            if (headerFromDb == null)
            {
                return Json(new { success = false, Message = "Error erasing header" });
            }

            _workContainer.Header.Remove(headerFromDb);
            _workContainer.Save();
            return Json(new { success = true, Message = "Header erased correctly" });
        }

        #endregion
    }
}

KleyTech/Areas/Admin/Controllers/PageClassController.cs
using KleyTech.Areas.User.Controllers;
using KleyTech.Data;
using KleyTech.DataAccess.Data.Repository.IRepository;
using KleyTech.Models;
using KleyTech.Models.ViewModels;
using KleyTech.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Packaging.Signing;

namespace KleyTech.Areas.Admin.Controllers
{
    [Authorize(Roles = CNT.Admin)]
    [Area("Admin")]
    public class PageClassController : Controller
    {
        private readonly IWorkContainer _workContainer;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PageClassController(IWorkContainer workContainer, IWebHostEnvironment webHostEnvironment)
        {
            _workContainer = workContainer;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PageClass pageClass)
        {

            if (ModelState.IsValid)
            {
                _workContainer.PageClass.Add(pageClass);
                _workContainer.Save();

                return RedirectToAction(nameof(Index));
            }

            return View(pageClass);

        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            PageClass pageClass = _workContainer.PageClass.Get(id);
            if (pageClass == null)
            {
                //return NotFound();
                pageClass = new PageClass { Name = "Main pageClass" };
                _workContainer.PageClass.Add(pageClass);
                _workContainer.Save();
            }

            return View(pageClass);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PageClass pageClass)
        {

            if (ModelState.IsValid)
            {
                _workContainer.PageClass.Update(pageClass);
                _workContainer.Save();

                return RedirectToAction(nameof(Index));
            }

            return View(pageClass);

        }

        #region Call to API

        [HttpGet]
        public IActionResult GetAll()
        {
            //Opcion1
            return Json(new { data = _workContainer.PageClass.GetAll() });
        }

        [HttpGet]
        public IActionResult ViewPage(int id)
        {
            HttpContext.Session.SetInt32("idPage",id);
            ViewData["IdPage"] = id;
            //HomeController home = new HomeController(_workContainer);
            return RedirectToAction("Index","Home",new { area = "User" });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var pageClassFromDb = _workContainer.PageClass.Get(id);
            if (pageClassFromDb == null)
            {
                return Json(new { success = false, Message = "Error erasing pageClass" });
            }

            _workContainer.PageClass.Remove(pageClassFromDb);
            _workContainer.Save();
            return Json(new { success = true, Message = "PageClass erased correctly" });
        }

        #endregion
    }
}

KleyTech/Areas/Admin/Controllers/SlidersController.cs
using KleyTech.Data;
using KleyTech.DataAccess.Data.Repository.IRepository;
using KleyTech.Models;
using KleyTech.Models.ViewModels;
using KleyTech.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Packaging.Signing;
using System.Data;

namespace KleyTech.Areas.Admin.Controllers
{
    [Authorize(Roles = CNT.Admin)]
    [Area("Admin")]
    public class SlidersController : Controller
    {
        private readonly IWorkContainer _workContainer;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public SlidersController(IWorkContainer workContainer, IWebHostEnvironment webHostEnvironment)
        {
            _workContainer = workContainer;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Slider slider)
        {

            if (ModelState.IsValid)
            {
                string MainRoute = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                var sliderFromDB = _workContainer.Slider.Get(slider.Id);

                if (files.Count > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var extension = Path.GetExtension(files[0].FileName);
                    var uploads = Path.Combine(MainRoute, @"images\sliders");

                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }

                    slider.ImageUrl = @"\images\sliders\" + fileName + extension;

                }

                _workContainer.Slider.Add(slider);
                _workContainer.Save();

                return RedirectToAction(nameof(Index));
            }

            return View(slider);

        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Slider slider = _workContainer.Slider.Get(id);
            if (slider == null)
            {
                return NotFound();
            }

            return View(slider);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Slider slider)
        {

            if (ModelState.IsValid)
            {
                string MainRoute = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                var sliderFromDB = _workContainer.Slider.Get(slider.Id);

                if (files.Count > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var extension = Path.GetExtension(files[0].FileName);
                    var uploads = Path.Combine(MainRoute, @"images\sliders");

                    if (sliderFromDB.ImageUrl.Length > 0)
                    {
                        var imageRoute = Path.Combine(MainRoute, sliderFromDB.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(imageRoute))
                        {
                            System.IO.File.Delete(imageRoute);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }

                    slider.ImageUrl = @"\images\sliders\" + fileName + extension;

                }
                else
                {
                    slider.ImageUrl = sliderFromDB.ImageUrl;
                }

                _workContainer.Slider.Update(slider);
                _workContainer.Save();

                return RedirectToAction(nameof(Index));
            }

            return View(slider);

        }

        #region Call to API

        [HttpGet]
        public IActionResult GetAll()
        {
            //Opcion1
            return Json(new { data = _workContainer.Slider.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var sliderFromDb = _workContainer.Slider.Get(id);
            string imageMainRoute = _webHostEnvironment.WebRootPath;
            if (sliderFromDb.ImageUrl != null)
            {
                var imageRoute = Path.Combine(imageMainRoute, sliderFromDb.ImageUrl.TrimStart('\\'));
                if (System.IO.File.Exists(imageRoute))
                {
                    System.IO.File.Delete(imageRoute);
                }
            }
            if (sliderFromDb == null)
            {
                return Json(new { success = false, Message = "Error erasing slider" });
            }

            _workContainer.Slider.Remove(sliderFromDb);
            _workContainer.Save();
            return Json(new { success = true, Message = "Slider erased correctly" });
        }

        #endregion
    }
}

KleyTech/Areas/Admin/Controllers/UsersController.cs
using KleyTech.Data;
using KleyTech.DataAccess.Data.Repository.IRepository;
using KleyTech.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;

namespace KleyTech.Areas.Admin.Controllers
{
    [Authorize(Roles = CNT.Admin)]
    [Area("Admin")]
    public class UsersController : Controller
    {
        private readonly IWorkContainer _workContainer;

        public UsersController(IWorkContainer workContainer)
        {
            _workContainer = workContainer;
        }

        [HttpGet]
        public IActionResult Index()
        {
            //return View(_workContainer.User.GetAll());
            ClaimsIdentity? claimsIdentity = User?.Identity as ClaimsIdentity;
            if (claimsIdentity == null)
                return View(_workContainer.User.GetAll());

            var actualUser = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (actualUser == null)
                return View(_workContainer.User.GetAll());

            return View(_workContainer.User.GetAll(u => u.Id != actualUser.Value));
        }
        
        [HttpGet]
        public IActionResult Lock(string id)
        {
            if (id == null) {
                return NotFound();
            }

            _workContainer.User.LockUser(id);
            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet]
        public IActionResult Unlock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _workContainer.User.UnlockUser(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

KleyTech/Views/Shared/_AdminPanelPartial.cshtml
<!-- Admin panel -->
<style>
    body {
        position: relative;
        overflow-x: hidden;
        background-color: #CFD8DC;
    }

    body,
    html {
        height: 100%;
    }

    .nav .open > a,
    .nav .open > a:hover,
    .nav .open > a:focus {
        background-color: transparent;
    }

    /*-------------------------------*/
    /*           Wrappers            */
    /*-------------------------------*/

    #wrapper {
        padding-left: 0;
        -webkit-transition: all 0.5s ease;
        -moz-transition: all 0.5s ease;
        -o-transition: all 0.5s ease;
        transition: all 0.5s ease;
    }

        #wrapper.toggled {
            padding-left: 220px;
        }

    #sidebar-wrapper {
        z-index: 1000;
        left: 220px;
        width: 0;
        height: 100%;
        margin-left: -220px;
        overflow-y: auto;
        overflow-x: hidden;
        background: #1a1a1a;
        -webkit-transition: all 0.5s ease;
        -moz-transition: all 0.5s ease;
        -o-transition: all 0.5s ease;
        transition: all 0.5s ease;
    }

        #sidebar-wrapper::-webkit-scrollbar {
            display: none;
        }

    #wrapper.toggled #sidebar-wrapper {
        width: 220px;
    }

    /*-------------------------------*/
    /*     Sidebar nav styles        */
    /*-------------------------------*/
    .navbar {
        padding: 0;
    }

    .sidebar-nav {
        position: absolute;
        top: 0;
        width: 220px;
        margin: 0;
        padding: 0;
        list-style: none;
    }

        .sidebar-nav li {
            position: relative;
            line-height: 20px;
            display: inline-block;
            width: 100%;
        }

            .sidebar-nav li:before {
                content: '';
                position: absolute;
                top: 0;
                left: 0;
                z-index: -1;
                height: 100%;
                width: 3px;
                background-color: #1c1c1c;
                -webkit-transition: width .2s ease-in;
                -moz-transition: width .2s ease-in;
                transition: width .2s ease-in;
            }

            .sidebar-nav li:first-child a {
                color: #fff;
                background-color: #1a1a1a;
            }

            .sidebar-nav li:nth-child(5n+1):before {
                background-color: #ec1b5a;
            }

            .sidebar-nav li:nth-child(5n+2):before {
                background-color: #79aefe;
            }

            .sidebar-nav li:nth-child(5n+3):before {
                background-color: #314190;
            }

            .sidebar-nav li:nth-child(5n+4):before {
                background-color: #279636;
            }

            .sidebar-nav li:nth-child(5n+5):before {
                background-color: #7d5d81;
            }

            .sidebar-nav li:hover:before,
            .sidebar-nav li.open:hover:before {
                width: 100%;
                -webkit-transition: width .2s ease-in;
                -moz-transition: width .2s ease-in;
                -ms-transition: width .2s ease-in;
                transition: width .2s ease-in;
            }

            .sidebar-nav li a {
                display: block;
                color: #ddd;
                text-decoration: none;
                padding: 10px 15px 10px 30px;
            }

                .sidebar-nav li a:hover,
                .sidebar-nav li a:active,
                .sidebar-nav li a:focus,
                .sidebar-nav li.open a:hover,
                .sidebar-nav li.open a:active,
                .sidebar-nav li.open a:focus {
                    color: #fff;
                    text-decoration: none;
                    background-color: transparent;
                }

    .sidebar-header {
        text-align: center;
        font-size: 20px;
        position: relative;
        width: 100%;
        display: inline-block;
    }

    .sidebar-brand {
        height: 65px;
        position: relative;
        background: #212531;
        background: linear-gradient(to right bottom, #2f3441 50%, #212531 50%);
        padding-top: 1em;
    }

        .sidebar-brand a {
            color: #ddd;
        }

            .sidebar-brand a:hover {
                color: #fff;
                text-decoration: none;
            }

    .dropdown-header {
        text-align: center;
        font-size: 1em;
        color: #ddd;
        background: #212531;
        background: linear-gradient(to right bottom, #2f3441 50%, #212531 50%);
    }

    .sidebar-nav .dropdown-menu {
        position: relative;
        width: 100%;
        padding: 0;
        margin: 0;
        border-radius: 0;
        border: none;
        background-color: #222;
        box-shadow: none;
    }

    .dropdown-menu.show {
        top: 0;
    }

    /*-------------------------------*/
    /*       Hamburger-Cross         */
    /*-------------------------------*/

    .hamburger {
        position: fixed;
        top: 10px;
        z-index: 999;
        display: block;
        width: 32px;
        height: 32px;
        margin-left: 15px;
        background: transparent;
        border: none;
        -webkit-transition: all 0.5s ease;
        -moz-transition: all 0.5s ease;
        -o-transition: all 0.5s ease;
        transition: all 0.5s ease;
    }

        .hamburger:hover,
        .hamburger:focus,
        .hamburger:active {
            outline: none;
        }

        .hamburger.is-closed:before {
            content: '';
            display: block;
            width: 100px;
            font-size: 14px;
            color: #fff;
            line-height: 32px;
            text-align: center;
            opacity: 0;
            -webkit-transform: translate3d(0,0,0);
            -webkit-transition: all .35s ease-in-out;
        }

        .hamburger.is-closed:hover:before {
            opacity: 1;
            display: block;
            -webkit-transform: translate3d(-100px,0,0);
            -webkit-transition: all .35s ease-in-out;
        }

        .hamburger.is-closed .hamb-top,
        .hamburger.is-closed .hamb-middle,
        .hamburger.is-closed .hamb-bottom,
        .hamburger.is-open .hamb-top,
        .hamburger.is-open .hamb-middle,
        .hamburger.is-open .hamb-bottom {
            position: absolute;
            left: 0;
            height: 4px;
            width: 100%;
        }

        .hamburger.is-closed .hamb-top,
        .hamburger.is-closed .hamb-middle,
        .hamburger.is-closed .hamb-bottom {
            background-color: #1a1a1a;
        }

        .hamburger.is-closed .hamb-top {
            top: 5px;
            -webkit-transition: all .35s ease-in-out;
        }

        .hamburger.is-closed .hamb-middle {
            top: 50%;
            margin-top: -2px;
        }

        .hamburger.is-closed .hamb-bottom {
            bottom: 5px;
            -webkit-transition: all .35s ease-in-out;
        }

        .hamburger.is-closed:hover .hamb-top {
            top: 0;
            -webkit-transition: all .35s ease-in-out;
        }

        .hamburger.is-closed:hover .hamb-bottom {
            bottom: 0;
            -webkit-transition: all .35s ease-in-out;
        }

        .hamburger.is-open .hamb-top,
        .hamburger.is-open .hamb-middle,
        .hamburger.is-open .hamb-bottom {
            background-color: #1a1a1a;
        }

        .hamburger.is-open .hamb-top,
        .hamburger.is-open .hamb-bottom {
            top: 50%;
            margin-top: -2px;
        }

        .hamburger.is-open .hamb-top {
            -webkit-transform: rotate(45deg);
            -webkit-transition: -webkit-transform .2s cubic-bezier(.73,1,.28,.08);
        }

        .hamburger.is-open .hamb-middle {
            display: none;
        }

        .hamburger.is-open .hamb-bottom {
            -webkit-transform: rotate(-45deg);
            -webkit-transition: -webkit-transform .2s cubic-bezier(.73,1,.28,.08);
        }

        .hamburger.is-open:before {
            content: '';
            display: block;
            width: 100px;
            font-size: 14px;
            color: #fff;
            line-height: 32px;
            text-align: center;
            opacity: 0;
            -webkit-transform: translate3d(0,0,0);
            -webkit-transition: all .35s ease-in-out;
        }

        .hamburger.is-open:hover:before {
            opacity: 1;
            display: block;
            -webkit-transform: translate3d(-100px,0,0);
            -webkit-transition: all .35s ease-in-out;
        }

    /*-------------------------------*/
    /*            Overlay            */
    /*-------------------------------*/

    .overlay {
        position: fixed;
        display: none;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: rgba(250,250,250,.8);
        z-index: 1;
    }
</style>

<div id="wrapper">
    <div class="overlay"></div>

    <!-- Sidebar -->
    <nav class="navbar navbar-inverse fixed-top" id="sidebar-wrapper" role="navigation">
        <ul class="nav sidebar-nav">
            <div class="sidebar-header">
                <div class="sidebar-brand">
                    <a asp-area="User" asp-controller="Home" asp-action="Index">Admin panel</a>
                </div>
            </div>
            <li><a asp-area="Admin" asp-controller="PageClass" asp-action="Index"><i class="fa-solid fa-file-circle-plus"></i> Pages</a></li>
            <li><a asp-area="Admin" asp-controller="Headers" asp-action="Index"><i class="fa-solid fa-code"></i> Headers</a></li>
            <li><a asp-area="Admin" asp-controller="Categories" asp-action="Index"><i class="fa-solid fa-sitemap"></i> Categories</a></li>
            @*<li><a href="#team">Team</a></li>
            <li class="dropdown">
                <a href="#works" class="dropdown-toggle" data-toggle="dropdown">Works <span class="caret"></span></a>
                <ul class="dropdown-menu animated fadeInLeft" role="menu">
                    <div class="dropdown-header">Dropdown heading</div>
                    <li><a href="#pictures">Pictures</a></li>
                    <li><a href="#videos">Videeos</a></li>
                    <li><a href="#books">Books</a></li>
                    <li><a href="#art">Art</a></li>
                    <li><a href="#awards">Awards</a></li>
                </ul>
            </li>*@
            <li><a asp-area="Admin" asp-controller="Articles" asp-action="Index"><i class="fa-solid fa-newspaper"></i> Articles</a></li>
            <li><a asp-area="Admin" asp-controller="Sliders" asp-action="Index"><i class="fa-regular fa-images"></i> Sliders</a></li>
            <li><a asp-area="Admin" asp-controller="Users" asp-action="Index"><i class="fa-solid fa-users"></i> Users</a></li>
        </ul>
    </nav>

KleyTech/Views/Shared/_Slider.cshtml
@model KleyTech.Models.ViewModels.HomeVM

@if (Model.Slider.Where(i=>i.Status).Count() > 0)
{

    <!-- Slider start -->
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">

            @{
                int cont = 0;
            }
            @foreach (var item in Model.Slider.Where(i => i.Status))
            {
                var dynamicItem = cont++ == 0 ? "item active" : "item";

                @if (item.Status == true)
                {
                    <div class="carousel-item @dynamicItem">
                        <img src="@Url.Content(item.ImageUrl)" class="d-block w-100">
                        <h2 class="text-white text-center bg-dark py-1">@Html.Raw(item.Name)</h2>
                    </div>
                }

            }

        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <!-- Slider End -->
}

KleyTech/Views/Shared/_ViewCreateAndReturn.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button>
    </div>
    &nbsp;
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Return</a>
    </div>
</div>